### ISSUE TITLE
Firefox directory under default/prefs ?

### ISSUE THREAD

**Issue by void-on-me** [ycatsh/firefox-themes#1]
what did you mean by going into your firefox directory? i tried going into $HOME/.mozilla/firefox/###.default-default but i don't see any default or prefs directory there.
can you please help me find what should i do to replicate Newtab as startpage as you did?

**Comment by ycatsh** [comment]
I'm assuming that you are running Linux, you can find where firefox is installed via `whereis firefox` in terminal. Usually, if you installed it directly from Mozilla the defaults folder should be in `usr/lib/firefox`

**Comment by void-on-me** [comment]
> I'm assuming that you are running Linux, you can find where firefox is installed via `whereis firefox` in terminal. Usually, if you installed it directly from Mozilla the defaults folder should be in `usr/lib/firefox`

oh now i figured out. thank you!  i fixed
