### ISSUE TITLE
License information?

### ISSUE THREAD

**Issue by rondDev** [ycatsh/firefox-themes#3]
Hi, I really like the styling you have on the homepage and I noticed you don't have a license on the repo, so I'm unsure what or if I'm allowed to use any of the code here?

**Comment by ycatsh** [comment]
Yeah, don't worry. You can use the code however you feel like. You can credit me or something in the repo if you make your own theme. I'll update the license now (I can't believe I forgot, haha).

**Comment by rondDev** [comment]
Thank you, and thanks for the quick response :)
