### ISSUE TITLE
Autoconfig.js is blocked by content security policy [Win11]

### ISSUE THREAD

**Issue by Lucksinia** [ycatsh/firefox-themes#4]
So, I really like your ~~smartfox~~ boring fox preset for firefox....

And it worked flawlessly so far from "out of the box" experience on any linux distro that I hopped in the last 3 month.

I tried to set it up on windows now, and failed miserably....

It loads cromeCSS (both, I presume) and then 
```
because it violates the following content security policy directive...
```
it blocks preload of autoconfig files... Which is not allowing them to load correct index page as a startpage.

**Comment by Lucksinia** [comment]
**Additional Images**
When opening:
![image](https://github.com/ycatsh/boring-fox/assets/63837173/ee22b241-4ca6-4f78-b9e8-519f4dcf688d)
On startpage:
![image](https://github.com/ycatsh/boring-fox/assets/63837173/fa7e87b9-d915-4596-b9ba-343d9763d498)
And on new page:
![image](https://github.com/ycatsh/boring-fox/assets/63837173/8e1d82a4-53bf-4a5a-a9cd-47f113df60f0)

And that's after when I started to tweak config, before only startpage(with notes and nothing else) worked.

**Comment by Lucksinia** [comment]
Well, I restarted Firefox 3 times, and now console doing .... CORS and two TypeErrors...
![image](https://github.com/ycatsh/boring-fox/assets/63837173/0db08916-deed-4b72-9805-9f921f184133)

in time.js it doesn't like amPM...
...and when loading askii it breaks on fetch request.

So, As I don't actually understand js...

Edit: I looked at warnings, and it seems that my instance of firefox does not allow loading js files... at all?
![image](https://github.com/ycatsh/boring-fox/assets/63837173/75df3233-0184-4cb9-b382-a94d75f88dcb)

**Comment by ChristoferMendes** [comment]
Im having the same issue :/. I'm on MacOS

**Comment by ycatsh** [comment]
@Lucksinia It has been fixed. It was because browsers don't allow reading local files without a server as it would be a massive security issue. Using `config.js` to store the configurations and importing it in other js files was bad design and it would never have worked. Sorry for that and the late response.
