### ISSUE TITLE
Unclear home page instructions

### ISSUE THREAD

**Issue by ChristoferMendes** [ycatsh/firefox-themes#5]
In the **Start Page** section, there is this text:

> 3. Change homepage under Firefox settings to 'Custom URLs' and _paste in the path._

I don't really understand what path it refers on: _paste in the path_.  I already configurated the css files and colors, just the homepage is lefting

**Comment by ycatsh** [comment]
The path where the index.html file is located (boring-fox/index.html). Sorry, I should've made that clear. 

Firefox basically uses that path to access the startpage and consequently show it on the browser.

**Comment by ChristoferMendes** [comment]
> The path where the index.html file is located (boring-fox/index.html). Sorry, I should've made that clear.
> 
> Firefox basically uses that path to access the startpage and consequently show it on the browser.

It should also be added inside autoconfig.cfg?

Also, the format of the path should be **_file:///path-to-default-release/boring-fox/index.html_**? On both cases?

**Comment by ycatsh** [comment]
Yes, precisely that.

**Comment by ChristoferMendes** [comment]
I did that, but now my homepage only shows the same on the issue: #4 (Mac)

**Comment by ycatsh** [comment]
Yes I'm working on that and will respond shortly. I was away for a long while so I couldn't get to it earlier. For now I'm closing this issue.
